name: Remove Artifact
description: Github Action for removing artifacts
author: Joonmo Yang
inputs:
  GITHUB_TOKEN:
    description: Access token for the repository.
    required: true
    default: ${{ github.token }}
  only-name:
    description: Exact string for filtering artifacts by name.
    required: false
  regex-name:
    description: Regex for filtering artifacts by name.
    required: false
  max-count:
    description: Maximum number of artifacts to keep.
    required: false
  max-age:
    description: Maximum age(by seconds) of artifacts to keep.
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'trash-2'
  color: 'orange'
